# -*- coding: utf-8 -*-
"""knnE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDze6I-2Z2N7GcH4WmWXmpf8CmexJN_H
"""

#-------------------------------------------------------------------------
# AUTHOR: Earaga Sellvan
# FILENAME: knn.py
# SPECIFICATION: LOO-CV with 1NN on email classification dataset
# FOR: CS 4210- Assignment #2
#-----------------------------------------------------------*/

# Import libraries
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

# Read dataset
df = pd.read_csv("email_classification.csv")

# Convert dataset into list of rows
db = df.values.tolist()

errors = 0
n = len(db)

# Loop over each row (Leave-One-Out Cross Validation)
for i in range(n):

    # Separate test sample
    testSample = db[i][0:20]  # first 20 columns = features
    testLabel = db[i][20]     # last column = class

    # Prepare training data
    X = []
    Y = []
    for j in range(n):
        if j != i:   # exclude test instance
            X.append([float(x) for x in db[j][0:20]])  # features
            Y.append(1 if db[j][20] == "spam" else 0)  # class: spam=1, ham=0

    # Fit 1NN model
    clf = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
    clf.fit(X, Y)

    # Predict test sample
    class_predicted = clf.predict([testSample])[0]

    # Convert actual label to number
    trueLabel = 1 if testLabel == "spam" else 0

    # Count error
    if class_predicted != trueLabel:
        errors += 1

# Compute error rate
error_rate = errors / n
print("1NN LOO-CV error rate:", error_rate)